version: 2
updates:
  # Mises à jour des modules Terraform / OpenTofu
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Mises à jour des GitHub Actions (sécurité des hashs SHA-1)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
