keys:
  - &host_caladan age1uxze7ur4xxj2r4zfx3mdkr2c6kslpgtfd52kh6r3s306xmtteceqj5nv6z
  - &host_ix age12vnun3ngclc3tnpq7r35v7azam2pkukxusxyj0n02wkx56cx3q3qf5wrwg
  - &flebel age1uxze7ur4xxj2r4zfx3mdkr2c6kslpgtfd52kh6r3s306xmtteceqj5nv6z
creation_rules:
  - path_regex: secrets/(common|vaultwarden)\.yaml$
    key_groups:
      - age:
          # caladan
          - age1uxze7ur4xxj2r4zfx3mdkr2c6kslpgtfd52kh6r3s306xmtteceqj5nv6z
          # ix
          - age12vnun3ngclc3tnpq7r35v7azam2pkukxusxyj0n02wkx56cx3q3qf5wrwg
  - path_regex: secrets/caladan\.yaml$
    key_groups:
      - age: [ *flebel, *host_caladan ]
  - path_regex: secrets/ix\.yaml$
    key_groups:
      - age: [ *flebel, *host_ix ]
