# Configuration Treefmt pour nix-config

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]



[formatter.deadnix]
command = "deadnix"
options = ["-e"]
includes = ["*.nix"]

[formatter.statix]
command = "statix"
options = ["fix"]
includes = ["*.nix"]
exclude = ["**/.agents/**"]
