# Configuration Treefmt pour nix-config

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.markdown]
command = "prettier"
options = ["--prose-wrap", "always"]
includes = ["*.md"]

[formatter.deadnix]
command = "deadnix"
options = ["-e"]
includes = ["*.nix"]

[formatter.statix]
command = "statix"
options = ["fix"]
includes = ["*.nix"]
