name: "Update Flake Lock"
on:
  schedule:
    - cron: "0 4 * * 1" # Tous les lundis à 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/update-flake-lock-action@v24
        with:
          pr-title: "chore(deps): mise à jour hebdomadaire des dépendances flake.lock"
          pr-labels: "dependencies,nix"
